# Generated by Django 5.1.1 on 2024-11-07 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem'),
        ('payments', '0002_productpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpayment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='order.order'),
        ),
    ]
