# Generated by Django 5.1.1 on 2024-10-16 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='sub_category',
        ),
    ]
