# Generated by Django 5.1.1 on 2024-10-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_category_products_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategories',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
