# Generated by Django 5.1.1 on 2024-10-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productimages_color_alter_productimages_product_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productimages',
            unique_together=set(),
        ),
    ]
