# Generated by Django 5.1.1 on 2024-10-25 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_productimages_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productdetails',
            constraint=models.UniqueConstraint(fields=('product', 'size', 'color'), name='unique_product_detail'),
        ),
    ]
