# Generated by Django 5.1.1 on 2024-10-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productdetails_unique_product_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategories',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
