# Generated by Django 5.1.1 on 2024-10-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_productsubcategories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategories',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='productsubcategories',
            unique_together={('name', 'category')},
        ),
    ]
