# Generated by Django 5.1.1 on 2024-10-23 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rating_whishlists'),
        ('store', '0008_alter_productimages_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whishlists',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='store.productdetails'),
        ),
    ]
