# Generated by Django 5.1.1 on 2024-10-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
