# Generated by Django 5.1.1 on 2024-11-07 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_useraddresses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
