# Generated by Django 5.1.1 on 2024-11-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_delete_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraddresses',
            unique_together=set(),
        ),
    ]
