# Generated by Django 5.1.1 on 2024-09-11 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='lesson',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='course_lesson', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='course_programs', to='courses.program'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='updated_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonimage',
            name='created_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_lesson_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonimage',
            name='updated_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_lesson_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonpdf',
            name='created_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_lesson_pdf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonpdf',
            name='updated_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_lesson_pdf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonvideo',
            name='created_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_lesson_video', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonvideo',
            name='updated_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_lesson_video', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='program',
            name='created_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='program',
            name='updated_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='batches', to='courses.course')),
                ('created_by', models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='instructed_batches', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
