# Generated by Django 5.1.1 on 2024-09-11 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_created_by_alter_course_lesson_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonimage',
            options={'verbose_name': 'Lesson Image', 'verbose_name_plural': 'Lesson Images'},
        ),
        migrations.AlterModelOptions(
            name='lessonpdf',
            options={'verbose_name': 'Lesson PDF', 'verbose_name_plural': 'Lesson PDFs'},
        ),
        migrations.AlterModelOptions(
            name='lessonvideo',
            options={'verbose_name': 'Lesson Video', 'verbose_name_plural': 'Lesson Videos'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='created_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batch',
            name='updated_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='course',
            name='lesson',
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='updated_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonimage',
            name='created_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonimage',
            name='updated_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonpdf',
            name='created_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonpdf',
            name='updated_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonvideo',
            name='created_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonvideo',
            name='updated_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='program',
            name='created_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='program',
            name='updated_by',
            field=models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_of_day', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], default='morning', max_length=10)),
                ('batch', models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sessions', to='courses.batch')),
                ('created_by', models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sessions', to='courses.lesson')),
                ('updated_by', models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='lesson',
            field=models.ManyToManyField(related_name='course_lessons', to='courses.lesson'),
        ),
    ]
