# Generated by Django 5.1.1 on 2024-09-14 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_batch_name_alter_course_name_alter_lesson_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='CourseWeekDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_description', to='courses.course')),
                ('created_by', models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default='Not Available', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course', 'week'), name='unique_course_week')],
            },
        ),
    ]
