# Generated by Django 5.1.1 on 2024-09-18 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_lesson_unique_lesson_week_session_unique_batch_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('course', 'name'), name='unique_batch_course'),
        ),
    ]
