# Generated by Django 5.1.1 on 2024-09-25 08:59

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_batchstudents_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='instructed_batches', to=settings.AUTH_USER_MODEL),
        ),
    ]
