# Generated by Django 5.1.1 on 2024-09-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_course_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchstudents',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='batchstudents',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='batchstudents',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='batchstudents',
            name='updated_by',
        ),
    ]
