# Generated by Django 5.1.1 on 2024-09-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_remove_batchstudents_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchstudents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-09-25 12:00:00'),
            preserve_default=False,
        ),
    ]
