# Generated by Django 5.1.1 on 2024-09-27 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_batchstudents_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='chapter',
            new_name='lesson_pdf',
        ),
    ]
