# Generated by Django 5.1.1 on 2024-09-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_rename_chapter_lesson_lesson_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ManyToManyField(related_name='lesson_image', to='courses.lessonimage'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_pdf',
            field=models.ManyToManyField(related_name='lesson_pdf', to='courses.lessonpdf'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.ManyToManyField(related_name='lesson_video', to='courses.lessonvideo'),
        ),
    ]
