# Generated by Django 5.1.1 on 2024-09-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_lesson_course_lesson_course'),
        ('courses', '0022_alter_lesson_image_alter_lesson_lesson_pdf_and_more'),
    ]

    operations = [
    ]
