# Generated by Django 5.1.1 on 2024-09-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_alter_lesson_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(default='default value'),
            preserve_default=False,
        ),
    ]
