# Generated by Django 5.1.1 on 2024-09-28 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_lesson_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_pdf',
            new_name='lesson_pdfs',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='video',
            new_name='videos',
        ),
    ]
