# Generated by Django 5.1.1 on 2024-10-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_lesson_lessonimage_lessonpdf_lessonvideo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonimage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lessonpdf',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lessonvideo',
            name='name',
        ),
    ]
