# Generated by Django 5.1.1 on 2024-10-03 05:19

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_remove_lessonimage_name_remove_lessonpdf_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='batch',
            name='end_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='batch',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='batch',
            name='strength',
            field=models.IntegerField(default=9, validators=[django.core.validators.MaxValueValidator(50)]),
            preserve_default=False,
        ),
    ]
