# Generated by Django 5.1.1 on 2024-10-03 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_remove_batch_time_slot_batch_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='strength',
            field=models.IntegerField(default=9, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
