# Generated by Django 5.1.1 on 2024-10-28 07:14

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0031_alter_batch_strength'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoChunks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_chunk', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.batch')),
            ],
        ),
    ]
