# Generated by Django 5.1.1 on 2024-10-30 04:31

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_room', '0002_videochunks_chunk_serial_and_more'),
        ('courses', '0031_alter_batch_strength'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('video', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video')),
                ('video_serial', models.IntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.batch')),
            ],
        ),
    ]
