# Generated by Django 5.1.1 on 2024-11-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_room', '0003_sessionvideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videochunks',
            name='record_id',
            field=models.CharField(null=True),
        ),
    ]
